# 大型ケージプロファイル (500×400mm)
# 大型ハムスター・複数飼い用ケージ設定

profile_info:
  name: "Large Hamster Cage 500x400"
  description: "Large cage profile for bigger hamsters or multiple subjects"
  version: "1.0"
  created_by: "System Default"
  suitable_for: ["golden_hamster", "multiple_subjects"]
  
cage:
  dimensions:
    width: 500.0
    height: 400.0  
    depth: 250.0
    
  specifications:
    material: "acrylic"
    corner_markers: true
    grid_pattern: false
    reference_object_size: 50.0
    background_color: "white"
    
  environment:
    camera_height_mm: 500.0           # 高い位置が必要
    lighting_type: "mixed"
    viewing_angle_degrees: 90.0

coordinate_calibration:
  method: "manual"
  calibration_points: 4
  validation:
    enabled: true
    reference_distance_mm: 150.0      # より大きな基準距離
    accuracy_threshold_mm: 8.0        # 大型ケージ用許容誤差

movement_tracking:
  constraints:
    max_speed_mm_per_sec: 250.0      # より高速移動対応
    max_acceleration_mm_per_sec2: 600.0
    min_movement_threshold_mm: 3.0    # より大きな最小移動量
    max_jump_distance_mm: 60.0
    
  filtering:
    kalman_filter_enabled: true
    smoothing_window_size: 7          # より大きなウィンドウ
    outlier_detection_enabled: true
    outlier_threshold_sigma: 2.5
    
  statistics:
    activity_threshold_mm_per_min: 120.0  # より高い活動量
    rest_threshold_sec: 400

optimization:
  deeplabcut:
    confidence_threshold: 0.65        # 距離による信頼度調整
    body_part_weights:
      nose: 0.2
      back: 0.3
      tail: 0.2
      
  lighting:
    rgb_correlation_threshold: 0.9
    
  performance:
    target_fps: 1.5                   # 処理負荷考慮