# 標準ケージプロファイル (380×280mm)
# ハムスター用標準アクリルケージ設定

profile_info:
  name: "Standard Hamster Cage 380x280"
  description: "Standard acrylic hamster cage profile"
  version: "1.0"
  created_by: "System Default"
  suitable_for: ["dwarf_hamster", "golden_hamster"]
  
cage:
  dimensions:
    width: 380.0
    height: 280.0  
    depth: 200.0
    
  specifications:
    material: "acrylic"
    corner_markers: true
    grid_pattern: false
    reference_object_size: 50.0
    background_color: "white"
    
  environment:
    camera_height_mm: 400.0
    lighting_type: "mixed"
    viewing_angle_degrees: 90.0

coordinate_calibration:
  method: "manual"
  calibration_points: 4
  validation:
    enabled: true
    reference_distance_mm: 100.0
    accuracy_threshold_mm: 5.0

movement_tracking:
  constraints:
    max_speed_mm_per_sec: 150.0      # ハムスター標準速度
    max_acceleration_mm_per_sec2: 400.0
    min_movement_threshold_mm: 2.0
    max_jump_distance_mm: 40.0
    
  filtering:
    kalman_filter_enabled: true
    smoothing_window_size: 5
    outlier_detection_enabled: true
    outlier_threshold_sigma: 2.0
    
  statistics:
    activity_threshold_mm_per_min: 80.0   # ハムスター用調整
    rest_threshold_sec: 300

# ケージ固有の最適化設定
optimization:
  deeplabcut:
    confidence_threshold: 0.7
    body_part_weights:
      nose: 0.25      # ハムスターは鼻での探索が多い
      back: 0.35      # 背中重視
      tail: 0.15      # 尻尾は軽め
      
  lighting:
    rgb_correlation_threshold: 0.85   # アクリル反射対応
    
  performance:
    target_fps: 2.0                   # 標準ケージ用FPS